<br /><br />
<div id="view-content">
    <p>View script for controller <b>Testimonial</b> and script/action name <b>index</b></p>

    <a href="<?php echo $this->url(array('controller' => 'testimonial', 'action' => 'write-testimonial')); ?>" >Click here to write your Testimonial! </a>

    <table>
        <tr>
            <th>Testimonial#</th><th>User/Date</th><th>Comment</th>
        </tr>
        <?php foreach ($this->testInfo as $dat) : ?>
            <tr>
                <td><?php echo $this->escape($dat->TESTMONIAL_ID); ?></td>
                <td>User
                <?php
                $accountid = $this->escape($dat->ACCOUNT_ID);

                foreach ($this->accountInfo as $mat):
                    if ($accountid == $this->escape($mat->ACCOUNT_ID)) {
                        echo $this->escape($mat->NAME);
                    }
                endforeach;
                ?>

                said on <?php echo $this->escape($dat->DATE); ?> </td>
            <td><?php echo $this->escape($dat->TEST_TEXT); ?></td>

        </tr>
<?php endforeach; ?>
    </table>

</div>